language: android
jdk: oraclejdk7

android:
  components:
	- build-tools-23
	- android-23

#script: pushd . && cd simple/ && ./gradlew shared:build && popd
before_script:
  - pushd . && cd simple/

after_script:
  - popd