# We have to configure the language in the matrix below.
language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode7
      language: objective-c
      env:
       - USING_OS=osx
       - USING_XCODE=7
# We can be run in a container for improved performance.
sudo: false

before_install:
  # Don't spew graphic art.
  - export TERM=dumb
  - env
  # Travis doesn't let us select the JDK version on OS X.  Force it ourselves.
  - if [ "$USING_OS" = "osx" ]; then ./install-osx-jdk7.sh; fi

# If these steps fail, the build is 'errored' - i.e. misconfigured.
# This can fail if we cannot download Gradle 2.4 or the libraries
# we depend on.
install:
  - if [ "$USING_OS" = "osx" ]; then ./install.sh; fi

before_script:
  - pushd . && cd simple
# If these steps fail, the build is 'failed' - i.e. we have a code defect.
# We compile (assemble) and then build (which also tests) to capture build
# and test failures separately.
script:
#  - ./gradlew assemble
#  - ./gradlew build
  # Run our system tests
  - if [ "$USING_OS" = "osx" ]; then ./gradlew :shared:build; fi
  
after_script:
  - popd
