language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a
android:
  components:
    - android-22
    - build-tools-22.0.1
before_script:
#  - ./install.sh
  - pushd . && cd simple/
script:
  - echo "hello"
  - ./gradlew app:build

after_script:
  - popd