language: android
sudo: false
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a
android:
  components:
    - android-23
    - build-tools-23.0.1
    - extra-android-support
    - extra-android-m2repository
before_script:
#  - ./install.sh
  - pushd . && cd simple/
script:
  - echo "hello"
  - ./gradlew clean build

after_script:
  - popd